stages:
  - deploy
deploy_to_test_env:
  stage: deploy
  image: python:3.9
  tags:
    - docker
  script:
    - export PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
    - pip install mkdocs mkdocs-material mkdocs-minify-plugin
    - mkdocs build
    # mkdocs serve -a 0.0.0.0:port 即可改为自动部署到测试环境，但是需要在docker中穿出对应的端口
  artifacts:
    paths:
      - site
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
      when: always

deploy_to_prod_env:
  stage: deploy
  image: python:3.9
  tags:
    - docker
  script:
    - export PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
    - pip install mkdocs mkdocs-material mkdocs-minify-plugin
    - mkdocs gh-deploy # 自动推送，这步请勿随意执行，直接会推送到生产环境
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always