# Copyright (c) 2016-2025 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: SHOVEL
site_url: https://github.com/diamond-shovel/diamond-shovel
site_author: hscsec
site_description: >-
  Shovel's Wiki

# Repository
repo_name: diamond-shovel
repo_url: https://github.com/diamond-shovel/diamond-shovel

# Copyright
copyright: Copyright &copy; 2024 - 2025 diamond-shovel Team

# Configuration·
theme:
  name: material
  language: zh
  #custom_dir: shovel/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: 切换到系统主题
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/favicon.ico
# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true


# Additional configuration
extra:

  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: G-KMFG578W80
  generator: false
  social:
    - icon: fontawesome/brands/weixin
      link: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=Mzg3Mzg1OTYyMQ==#wechat_redirect
    - icon: fontawesome/brands/github
      link: https://github.com/diamond-shovel/diamond-shovel
  consent: 
     title: Cookie consent 
     description: >- 
      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。 如果你同意,你可以帮助我们让我们的网站更好
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html  # 启用HTML混合模式
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

# Page tree
nav:
  - SHOVEL: index.md
  - 快速开始: quick-start.md
  - 入门:
    - 插件开发:
      - 基础插件: shovel-plugins.md
      - 中间件层: shovel-intermediate-layer.md
      - 插件开发指南: plugin.md
    - 使用指南:
      - 安装指南: https://github.com/diamond-shovel/diamond-shovel/blob/main/docs/install.md
      - 命令行使用: https://github.com/diamond-shovel/diamond-shovel/blob/main/docs/cmdline.md
  - 概念:
    - 概述:
      - 资产: Concepts/Assets.md
      - 资产组:Concepts/AssetGroup.md
      - 策略:
      - 任务:
      - 节点:
  - FAQ:
    - 安装: ./FAQ/stages/install/FAQ_install.md
    - 插件: ./FAQ/stages/plugins/plugins.md
  - 项目信息:
    - 项目主页: Readme.md
    - 贡献指南: https://github.com/diamond-shovel/diamond-shovel/blob/main/CONTRIBUTING.md
    - 行为准则: https://github.com/diamond-shovel/diamond-shovel/blob/main/CODE_OF_CONDUCT.md
    - 安全汇报: https://github.com/diamond-shovel/diamond-shovel/blob/main/SECURITY.md
    - 项目许可: https://github.com/diamond-shovel/diamond-shovel/blob/main/LICENSE.md
    - GitHub仓库: https://github.com/diamond-shovel/diamond-shovel
    - README文档: https://github.com/diamond-shovel/diamond-shovel/blob/main/README.md
